contact/urls.py
from django.contrib import admin
from django.urls import path
from contact import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'contact'

urlpatterns = [
    path('',views.index,name='index'),
    path('search/',views.search, name='search'),
    path('add/',views.add, name='add'),
    path('single-contact/<int:num>', views.single_contact, name='single-contact'),
    path('single-contact/delete/<int:num>', views.delete, name='delete'),
    path('single-contact/edit/<int:num>', views.edit, name='edit'),
    path('user/register',views.register,name='register'),
    path('user/login', views.login_view,name='login'),
    path('user/logout', views.logout_view,name='logout'),
    path('user/login/change_password', views.change_password, name='chpassword'),
    path('user/login/delete', views.delete_user, name='delete-user'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('contact.urls'))
]

contact/models.py
from django.db import models
from PIL import Image
from io import BytesIO
from django.core.files import File
from django.contrib.auth.models import User
# Create your models here.

class Contact(models.Model):
    
    name = models.CharField(
        verbose_name='Nome',
        max_length=255,
        null=False,
        )
    last_name = models.CharField(
        verbose_name='Sobrenome',
        max_length=255,
        null=False,
    )
    number = models.BigIntegerField(
        verbose_name='Telefone',
        max_length=13,
        null=False,
        )
    email = models.EmailField(
        verbose_name='Email',
        max_length=255,
        blank=True,
        default='',
    )
    category = models.ForeignKey(
        to='Categories',
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        default='',
        related_name='+')
    image = models.ImageField(
        verbose_name='Foto',
        blank=True,
        null=True,
        upload_to='media/photos',
    )
    owner = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        null=True,
    )

    def __str__(self):
        return f'{self.name} {self.last_name}'
    
    def resize_img(self,img):
        import os
        _name, _type = os.path.splitext(img.__str__())
        size=(150,200)
        
        with Image.open(img) as im:
            im = im.resize(size)
            im_io = BytesIO() 
            im.save(im_io, 'JPEG', quality=100, optimize=True) 

            new_image = File(im_io, name=img.name)
            return new_image

    def save(self, *args, **kwargs):
        if self.image:
            new_image = self.resize_img(self.image)
            self.image = new_image
        return super().save(*args, **kwargs)

        # size = (100,150)
        # with Image.open(img) as im:
        #     ImageOps.contain(im,size).save(f'{img.__str__()}.jpg')

class Categories(models.Model):
    categories = models.CharField(
        verbose_name='Categoria',
        max_length=255,
        blank=True,
    )

    def __str__(self):
        return f'{self.categories}'
    
    class Meta:
        verbose_name_plural = 'Categories'
        
    

contact/views.py
from django.shortcuts import render, redirect
from contact.models import Contact
from django.core.paginator import Paginator
from contact.form import ContactForm, RegisterForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User

#from django.urls import reverse

#from PIL import Image
# Create your views here.

def index(request):

    contatos = Contact.objects.all()
    p = Paginator(contatos,8)

    page_number = request.GET.get('page')
    page_obj = p.get_page(page_number)
    context = {
        'page_obj':page_obj,
    }
    return render(
        request,
        'contact/index.html',
        context = context,
    )

def search(request):
    q = request.GET.get('q').strip().lower()
    contatos = Contact.objects.all()
    list_contacts = set()

    for i in contatos:
        if i.name.lower() == q:
            list_contacts.add(i)
        elif i.last_name.lower() == q:
            list_contacts.add(i)
        elif q in i.number:
            list_contacts.add(i)
    list_contacts = list(list_contacts)
    p = Paginator(list_contacts,8)

    page_number = request.GET.get('page')
    page_obj = p.get_page(page_number)
    context = {
        'page_obj':page_obj,
        'q':q,
    }
    return render(
        request,
        'contact/index.html',
        context = context,
    )

def add(request):
    if request.method == 'POST':

        form = ContactForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            return redirect("contact:index")
    else:
        form = ContactForm()

    context = {
        'form': form,
    }
    return render(
        request,
        'contact/add.html',
        context=context
        )

def single_contact(request, num):

    contato = Contact.objects.get(id__exact=num)
    # print(type(contato.image))
    # contato.image = contato.resize_img(contato.image)
    # print(type(contato.image))
    # out.show()
    context = {
            'contato':contato,
            }
    return render(
        request,
        'contact/sgcontact.html',
        context=context,
        )

def delete(request,num):
    
    confirmation = request.POST.get('confirmation')
    
    if confirmation == 'no':

        contato = Contact.objects.get(id__exact=num)
        context= {
            'contato':contato,
            'confirmation':'yes'
        }
        # contato.delete()
        # return redirect("contact:delete", num)
        return render(request,'contact/sgcontact.html',context=context)
    else:
        contato = Contact.objects.get(id__exact=num)
        contato.delete()
        return redirect('contact:index')
    
def edit(request, num):

    contato = Contact.objects.get(id__exact=num)
    
    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES, instance=contato)

        if form.is_valid():
            form.save()
            return redirect('contact:index')

    form = ContactForm(instance=contato)
    context = {
        'contato':contato,
        'form':form,
    }
    return render(
        request,
        'contact/edit.html',
        context=context

    )

def register(request):
    form = RegisterForm()
    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            form.save()
            messages.info(request,'Usuário salvo')

            return redirect('contact:index')
        # return redirect('contact:index')
        messages.error(request,'Usuário não salvo')

    context = {
        'form':form,
    }
    return render(
        request,
        'contact/register.html',
        context=context,
    )

def login_view(request):

    form=AuthenticationForm(request)
    
    if request.user:
        user_name = request.user
        try:
            user_data = User.objects.get(username=user_name)
            print(user_data.username)
        except:
            pass

    if request.method == 'POST':
        form=AuthenticationForm(request,data=request.POST)

        if form.is_valid():
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request,username=username,password=password)

            if user is not None:
                login(request,user)
                messages.success(request,'Usuário foi logado')

                return redirect('contact:index')
            
        else:
            messages.error(request,'Login inválido')
            
    context={
        'form':form,
    }
    return render(
        request,
        'contact/login.html',
        context=context,
    )

def logout_view(request):
    logout(request)
    return redirect('contact:index')

contact/views/contact_views.py
from django.shortcuts import render, redirect
from contact.models import Contact
from contact.form import ContactForm
from django.contrib import messages

def add(request):
    if request.method == 'POST':

        form = ContactForm(request.POST, request.FILES)

        if form.is_valid():
            contact = form.save(commit=False)
            contact.owner = request.user
            contact.save()
            return redirect("contact:index")
    else:
        form = ContactForm()

    context = {
        'form': form,
    }
    return render(
        request,
        'contact/add.html',
        context=context
        )

def single_contact(request, num):

    contato = Contact.objects.get(id__exact=num)
    # print(type(contato.image))
    # contato.image = contato.resize_img(contato.image)
    # print(type(contato.image))
    # out.show()
    context = {
            'contato':contato,
            }
    return render(
        request,
        'contact/sgcontact.html',
        context=context,
        )

def delete(request,num):
    
    confirmation = request.POST.get('confirmation')
    
    if confirmation == 'no':

        contato = Contact.objects.get(id__exact=num)
        context= {
            'contato':contato,
            'confirmation':'yes'
        }
        # contato.delete()
        # return redirect("contact:delete", num)
        return render(request,'contact/sgcontact.html',context=context)
    else:
        contato = Contact.objects.get(id__exact=num)
        contato.delete()
        return redirect('contact:index')
    
def edit(request, num):

    contato = Contact.objects.get(id__exact=num)
    
    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES, instance=contato)

        if form.is_valid():
            form.save()
            return redirect('contact:index')

    form = ContactForm(instance=contato)
    context = {
        'contato':contato,
        'form':form,
    }
    return render(
        request,
        'contact/edit.html',
        context=context

    )

contact/views/user_views.py
from django.shortcuts import render, redirect
from contact.models import Contact
from django.core.paginator import Paginator
from contact.form import RegisterForm
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.models import User

def index(request):

    contatos = Contact.objects.all()
    p = Paginator(contatos,8)

    page_number = request.GET.get('page')
    page_obj = p.get_page(page_number)
    context = {
        'page_obj':page_obj,
    }
    return render(
        request,
        'contact/index.html',
        context = context,
    )

def search(request):
    q = request.GET.get('q').strip().lower()
    contatos = Contact.objects.all()
    list_contacts = set()

    for i in contatos:
        if i.name.lower() == q:
            list_contacts.add(i)
        elif i.last_name.lower() == q:
            list_contacts.add(i)
        elif q in str(i.number):
            list_contacts.add(i)
    list_contacts = list(list_contacts)
    p = Paginator(list_contacts,8)

    page_number = request.GET.get('page')
    page_obj = p.get_page(page_number)
    context = {
        'page_obj':page_obj,
        'q':q,
    }
    return render(
        request,
        'contact/index.html',
        context = context,
    )

def register(request):
    form = RegisterForm()
    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            form.save()
            messages.info(request,'Usuário salvo')

            return redirect('contact:index')
        # return redirect('contact:index')
        messages.error(request,'Usuário não salvo')

    context = {
        'form':form,
    }
    return render(
        request,
        'contact/register.html',
        context=context,
    )

def login_view(request):

    form=AuthenticationForm(request)

    if request.method == 'POST':
        form=AuthenticationForm(request,data=request.POST)

        if form.is_valid():
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request,username=username,password=password)

            if user is not None:
                login(request,user)
                messages.success(request,'Usuário logado')

                return redirect('contact:index')
            
        else:
            messages.error(request,'Login inválido')
            
    context={
        'form':form,
    }
    return render(
        request,
        'contact/login.html',
        context=context,
    )

def logout_view(request):
    logout(request)
    messages.success(request,'Usuário deslogado')
    return redirect('contact:index')

def change_password(request):
    form = PasswordChangeForm(request.user)
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, "Sua senha foi alterada com sucesso!")
            return redirect('contact:login')
        else:
            messages.error(request, "Por favor, coloque uma senha válida")

    context = {
        'form':form,
    }
    return render(
        request,
        'contact/chpassword.html',
        context=context
    )

def delete_user(request):

    confirm = request.POST['confirm']

    if confirm == 'yes':
        usuario = User.objects.get(username=request.user)
        usuario.delete()
        messages.success(request,'Usuário deletado com sucesso')
        return redirect('contact:index')
    
    context={
        'confirm':'yes',
    }

    return render(
        request,
        'contact/login.html',
        context=context,
    )

contact/templates/contact/add.html
{% extends "base.html" %}
{% block add %}
    <div class="main-content">
        <div class="contact-content">
            <div class="row-content">
                <h2>Criação de contato</h2>
            </div>
            <div class="row-content">
                <form action="{% url "contact:add" %}" method="post" class="add-form" enctype="multipart/form-data">
                    {% csrf_token %}
                    

                        {% for field in form %}
                            <div class="field-content">
                                <label for="field.id_for_label" class="field-label">{{field.label}}</label>                    
                                {{field}}
                                {% if field.errors %}<span class='field-error'>{{field.errors}}</span>{% endif %}
                                {% if field.help_text %}<span class='field-help-text'>{{field.help_text}}</span>{% endif %}
                            </div>
                        {% endfor %}
                        
                        <div class="div-button">
                            <input type="submit" value="Adicionar" class="button-form button-padding green-button">
                            <input type="reset" value="Resetar" class="button-form button-padding yellow-button">
                            <button type="button" class="button-form red-button">
                                <a href="{% url "contact:index" %}" style="color: inherit;">
                                    Cancelar
                                </a>
                            </button>
                        </div>
                    
                </form>
            </div>
        </div>
    </div>
{% endblock add %}

contact/templates/contact/chpassword.html
{% extends "base.html" %}
{% block login %}
    <div class="main-content">
        <div class="contact-content">
            <div class="row-content">
                <form action="{% url "contact:chpassword" %}" method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="field-content">
                            <label for="field.id_for_label" class="field-label">{{field.label}}</label>                    
                            {{field}}
                            {% if field.errors %}<span class='field-error'>{{field.errors}}</span>{% endif %}
                            {% if field.help_text %}<span class='field-help-text'>{{field.help_text}}</span>{% endif %}
                        </div>
                    {% endfor %}

                    <div class="div-button">
                        <input type="submit" value="Salvar" class="button-form button-padding green-button">
                        <button type="button" class="button-form red-button">
                            <a href={% url "contact:login" %} style="color: inherit;">Cancelar</a></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock login %}


contact/templates/contact/edit.html
{% extends "base.html" %}
{% block edit %}
    <div class="main-content">
        <div class="contact-content">
            <div class="row-content">
                <h2>Edição de contato</h2>
            </div>
            <div class="row-content">
                <form action="{% url "contact:edit" contato.id %}" method="post" class="edit-form" enctype="multipart/form-data">
                    {% csrf_token %}
                    

                        {% for field in form %}
                            <div class="field-content">
                                {% if field.label != 'Foto' %}
                                    <label for="field.id_for_label" class="field-label">{{field.label}}</label>                    
                                    {{field}}
                                    {{field.errors}}
                                {% else %}
                                    <label for="field.id_for_label" class="field-label">{{field.label}}</label>
                                    <br>
                                    {{field}}
                                {% endif %}
                            </div>
                        {% endfor %}
                        
                        <div class="div-button">
                            <input type="submit" value="Salvar" class="button-form button-padding green-button">
                            <button type="button" class="button-form red-button">
                                <a href="{% url "contact:index" %}" style="color: inherit;">
                                    Cancelar
                                </a>
                            </button>
                        </div>
                    
                </form>
            </div>
        </div>
    </div>
{% endblock edit %}

contact/templates/contact/index.html
{% extends "base.html" %}

{% block index %}
    {% if page_obj %}
        <div class="main-content">
            <div class="index-content">
                <table class="table-content">
                    <caption class="table-caption">
                        <div>
                            <h3 class="title-white">Contatos</h3>
                            {% include "partials/search-box.html" %}
                        </div>
                    </caption>
                    <tr class="table-row table-row-header">
                        <th class="table-header">ID</th>
                        <th class="table-header">Nome</th>
                        <th class="table-header">Sobrenome</th>
                        <th class="table-header">Telefone</th>
                    </tr>
                    {% for contato in page_obj %}
                        <tr class="table-row">
                            
                            <td class="table-cel"><a href="{% url "contact:single-contact" contato.id %}" class="table-link">{{contato.id}}</a></th>
                            <td class="table-cel">{{contato.name}}</th>
                            <td class="table-cel">{{contato.last_name}}</th>
                            <td class="table-cel">{{contato.number}}</th>
                        </tr>
                    {% endfor %}
                    
                </table>

                <div class="pagination">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                            <a href="?page=1&q={{q}}">&laquo; Primeiro</a>
                            <a href="?page={{page_obj.previous_page_number}}&q={{q}}">Anterior</a>
                        {% endif %}

                        <span class="current">
                            Página {{page_obj.number}} de {{page_obj.paginator.num_pages}}.
                        </span>

                        {% if page_obj.has_next %}
                            <a href="?page={{page_obj.next_page_number}}&q={{q}}">Próximo</a>
                            <a href="?page={{page_obj.paginator.num_pages}}&q={{q}}">Último &raquo;</a>
                        {% endif %}
                    </span>
                </div>
            </div>
        </div>
    {% else %}
        <div class="main-content">
            <div class="index-content">
                <table class="table-content">
                    <caption class="table-caption">
                        <div>
                            <h3 class="title-white">Contatos</h3>
                            {% include "partials/search-box.html" %}
                        </div>
                    </caption>
                    <tr class="table-row">
                        <td class="table-cel">
                            <span style="font-weight: bold; font-size: 1.2rem;">
                                Contato não encontrado
                            </span>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    {% endif %}
    
{% endblock index %}


contact/templates/contact/login.html
{% extends "base.html" %}
{% block login %}
<div class="main-content">
    <div class="contact-content">

        {% if not user.is_authenticated %}
        <div class="row-content">
            <h2>Login de usuário</h2>
        </div>
        <div class="row-content">
            <form action="{% url "contact:login" %}" method="post" class="login-form" enctype="multipart/form-data">
                {% csrf_token %}
                

                    {% for field in form %}
                        <div class="field-content">
                            <label for="field.id_for_label" class="field-label">{{field.label}}</label>                    
                            {{field}}
                            {% if field.errors %}<span class='field-error'>{{field.errors}}</span>{% endif %}
                            {% if field.help_text %}<span class='field-help-text'>{{field.help_text}}</span>{% endif %}
                        </div>
                    {% endfor %}
                    
                    <div class="div-button">
                        <input type="submit" value="Logar" class="button-form button-padding green-button">
                        <button type="button" class="button-form red-button">
                            <a href="{% url "contact:index" %}" style="color: inherit;">
                                Cancelar
                            </a>
                        </button>
                    </div>
                
            </form>
        </div>
        {% else %}
            <div class="row-content mobile-title">
                <h2>Usuário</h2>
                <a href={% url "contact:index" %} class="back-button">Voltar</a>
            </div>
            <div class="row-content">
                <ul class="sg-contact-list">
                    <li class="sg-contact-item">
                        <p>Usuário: {{user}}</p>
                    </li>
                    <li class="sg-contact-item">
                        <p>Nome: {{user.first_name}}</p>
                    </li>
                    <li class="sg-contact-item">
                        <p>Sobrenome: {{user.last_name}}</p>
                    </li>
                    <li class="sg-contact-item">
                        <p>Email: {{user.email}}</p>
                    </li>
                    
                </ul>
            </div>

            <div class="row-content">
                <form action={% url 'contact:delete-user' %} method="post">
                    {% csrf_token %}
                    <div class="div-button">
                        <button type="button" class="button-form yellow-button">
                            <a href="{% url "contact:chpassword" %}" style="color: inherit;">
                                Trocar Senha
                            </a>
                        </button>
                        {% if confirm != 'yes' %}
                            <button type="submit" class="button-form button-padding red-button">Deletar conta</button>
                            <input type="hidden" value="no" id='confirm' name='confirm'> 

                        {% else %}
                            <button type="submit" class="button-form button-padding red-button">Confirma?</button>
                            <input type="hidden" value="yes" id='confirm' name='confirm'>
                        {% endif %}
                    </div>
                </form>
            </div>
        {% endif %}
    </div>
</div>

{% endblock login %}


contact/templates/contact/register.html
{% extends "base.html" %}
{% block register %}
    <div class="main-content">
        <div class="contact-content">
            <div class="row-content">
                <h2>Criação de usuário</h2>
            </div>
            <div class="row-content">
                <form action="{% url "contact:register" %}" method="post" class="register-form" enctype="multipart/form-data">
                    {% csrf_token %}
                    

                        {% for field in form %}
                            <div class="field-content">
                                <label for="field.id_for_label" class="field-label">{{field.label}}</label>                    
                                {{field}}
                                {% if field.errors %}<span class='field-error'>{{field.errors}}</span>{% endif %}
                                {% if field.help_text %}<span class='field-help-text'>{{field.help_text}}</span>{% endif %}
                            </div>
                        {% endfor %}
                        
                        <div class="div-button">
                            <input type="submit" value="Salvar" class="button-form button-padding green-button">
                            <input type="reset" value="Resetar" class="button-form button-padding yellow-button">
                            <button type="button" class="button-form red-button">
                                <a href="{% url "contact:index" %}" style="color: inherit;">
                                    Cancelar
                                </a>
                            </button>
                        </div>
                    
                </form>
            </div>
        </div>
    </div>
{% endblock register %}

contact/templates/contact/sgcontact.html
{% extends "base.html" %}

{% block sgcontact %}
    <div class="main-content">
        <div class="contact-content">
            <div class="row-content mobile-title">
                <h2>Contato</h2>
                <a href={% url "contact:index" %} class="back-button">Voltar</a>
            </div>
            
            <div class="row-content">
                <ul class="sg-contact-list">
                    <li class="sg-contact-item">
                        <span class="label-item">Nome:</span> {{contato.name}}
                    </li>
                    <li class="sg-contact-item">
                        <span class="label-item">Sobrenome:</span> {{contato.last_name}}</li>
                    <li class="sg-contact-item">
                        <span class="label-item">Telefone:</span> {{contato.number}}</li>
                    {% if contato.email %}
                        <li class="sg-contact-item">
                            <span class="label-item">Email:</span> {{contato.email}}</li>
                    {% endif %}
                    {% if contato.category %}
                        <li class="sg-contact-item">
                            <span class="label-item">Categoria:</span> {{contato.category}}</li>
                    {% endif %}
                    {% if contato.image %}
                        <li class="sg-contact-item">
                            <img src="{{contato.image.url}}" alt=f"{{contato.name}} {{contato.last_name}}">
                    {% endif %}
                    
                    {% if user == contato.owner %}
                        <form action="{% url "contact:delete" contato.id %}" method="post" class="sgcontact-form">
                            <div class="div-button">
                                {% csrf_token %}
                                
                                
                                <button type="button" class="button-form yellow-button">
                                    <a href="{% url "contact:edit" contato.id %}" style="color: inherit;">Editar</a>
                                </button>

                                {% if confirmation == 'yes' %}
                                    <button type="submit" class="button-form button-padding red-button">Confirma?</button>
                                {% else %}
                                    <button type="submit" class="button-form button-padding red-button">Delete</button>
                                    <input type="hidden" name='confirmation' id="confirmation" value="no">
                                {% endif %}
                            </div>
                        </form>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
{% endblock sgcontact %}